# Generated by Django 4.0.5 on 2022-09-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_day', models.CharField(max_length=20)),
                ('tasks', models.CharField(max_length=200)),
                ('happiness_score', models.IntegerField(default=0)),
            ],
        ),
    ]
