# Generated by Django 4.0.5 on 2022-09-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_day', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='data',
            name='happiness_score',
            field=models.IntegerField(),
        ),
    ]
