# Generated by Django 4.0.5 on 2022-10-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_analysis_delete_product_alter_data_happiness_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='happiness_score',
            field=models.FloatField(),
        ),
    ]
